\input texinfo
@setfilename example.info
@settitle Texinfo Example

@ifnottex
@node Top
@top Пример
Это пример документа Texinfo.
@end ifnottex

@menu
* Введение:: Определения, Меры, Сложность
* Исчисление полиномов::  Изучение обычных операций
@end menu

@node Введение
@chapter Введение
В этой главе обсуждаются концепции, в дальнейшем используемые
в разных частях этого документа. Более того, здесь вводятся
мера эффективности и мера ограничения сложности.

@menu
* Определения:: Основы
* Меры эффективности:: Как измерять эффективность
* Ограничения сложности:: Типичные ограничения сложности
@end menu

@node Определения
@section Определения
abla

@node Меры эффективности
@section Меры эффективности
obla

@node Ограничения сложности
@section Ограничения сложности
ebla

@node Исчисление полиномов
@chapter Исчисление полиномов
bla
@bye
