#!/bin/sh
#
# Config was made by Necromant
# shell scipt for execution lock botton
# // note: works with systemd systems only

lock() {
    i3lock
}

case "$1" in
    lock)
        exec "~/.i3/i3lock.sh";;
    kill)
        xkill;;
    switch_user)
	    dm-tool switch-to-greeter;;
    suspend)
        systemctl suspend;;
    hibernate)
	    systemctl hibernate;;
    reboot)
        systemctl reboot;;
    shutdown)
	    systemctl poweroff;;
    *)
        echo "Usage: $0 {lock|kill|switch_user|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
